DROP PROCEDURE STDDEV_SAL@

CREATE PROCEDURE STDDEV_SAL(stddev DECIMAL(10,2))
  LANGUAGE SQL
  BEGIN

    DECLARE SQLSTATE CHAR(5) DEFAULT '00000';
    DECLARE CURRENT_SALARY DECIMAL(10,2);
    DECLARE SUM_SALARY DECIMAL(30,2);
    DECLARE SUM_SALARY_SQUARE DECIMAL(30,2);
    DECLARE COUNTER INTEGER;

    DECLARE c CURSOR FOR SELECT SALARY FROM EMPLOYEE;

      SET SUM_SALARY = 0;
      SET SUM_SALARY_SQUARE = 0;
      SET COUNTER = 0;

      OPEN c;

      FETCH FROM c INTO CURRENT_SALARY;

      WHILE(SQLSTATE = '00000') DO

        SET SUM_SALARY = SUM_SALARY + CURRENT_SALARY;
        SET SUM_SALARY_SQUARE = SUM_SALARY_SQUARE + POWER(CURRENT_SALARY,2);
        SET COUNTER = COUNTER+1;
        FETCH FROM c INTO CURRENT_SALARY;

      END WHILE;

      CLOSE c;

      SET stddev = SQRT((SUM_SALARY_SQUARE/COUNTER) - POWER((SUM_SALARY/COUNTER),2));

      CALL DBMS_OUTPUT.PUT( 'Standard deviation: ' );
      CALL DBMS_OUTPUT.PUT_LINE( stddev );

  END@


SET SERVEROUTPUT ON@

CALL STDDEV_SAL('0.00')@

SET SERVEROUTPUT OFF@
